Add files via upload

diff --git a/home/homeowner/bashttpd b/home/homeowner/bashttpd
--- a/home/homeowner/bashttpd
+++ b/home/homeowner/bashttpd
@@ -481,9 +481,9 @@ A:active  { color : #000000; font-weight: normal; background-color : transparent
 
 #jpg?aliased?mostrecent'+...
 function serve_dir_or_file_from() {
-#echo "${URL_PATH}" >> /var/log/bashttpd.log
-echo "1. ${1}/${3}" > /var/log/bashttpd.log
-  local URL_PATH="${1}/${3}"
+#echo "${URL_PATH}" > /var/log/bashttpd.log
+echo "1. ${1} + / + ${3}" > /var/log/bashttpd.log
+  [[ ! "${3}." == "." ]] && local URL_PATH="/${3}" || local URL_PATH="${1}/${3}"
   shift
   URL_PATH=$(urldecode "${URL_PATH}") 
 echo "2. ${URL_PATH}" >> /var/log/bashttpd.log
@@ -578,9 +578,12 @@ fi
    # Serve index file if exists in requested directory 
   [[ -d "${URL_PATH}" && -f "${URL_PATH}/index.html" && -r "${URL_PATH}/index.html" ]] && \
      URL_PATH="${URL_PATH}/index.html"
+echo "3. ${URL_PATH}" >> /var/log/bashttpd.log
   if [[ -f "${URL_PATH}" ]] && [[ ! "${URL_PATH}" =~ latest.jpg$ ]] || [[ $OPENHERE == "true" ]]; then
      [[ -r "${URL_PATH}" ]] &&  serve_file "${URL_PATH}" "$@" || fail_with 403
-
+#  elif [[ -f "${1}" ]] && [[ ! "${URL_PATH}" =~ latest.jpg$ ]] || [[ $OPENHERE == "true" ]]; then
+#     echo "4. ${1}" >> /var/log/bashttpd.log
+#     [[ -r "${1}" ]] &&  serve_file "${1}" "$@" || fail_with 403
 #grep_options to include -v for MOTION,head_options to include mostrecent, settimeout, aliased, nextbymodifiedtime, [0-9.]{1,2}minutesbefore*, 
 #GREP_OPTIONS=""
 #HEAD_OPTIONS="head -n${URL_PATH##*mostrecent}";URL_PATH="${URL_PATH%%.mostrecent*}"
@@ -1340,7 +1343,7 @@ function start_media_daemon() {
 } 
 
 function main() { 
-LINKPRE="$(ip -o address|grep 'eno1    inet '|cut -c 17-35|cut -d/ -f1)\:${LISTEN_PORT}"
+LINKPRE="$(</etc/network/if-up.d/thisipadd.txt)\:${LISTEN_PORT}"
  local recv="" 
  # line variable is used in serve_dir_with_tree() so it is global.
  line="" 
